site_name: GeoNodes
site_description: Python API for Blender Geometry Nodes
site_author: al1brn
site_url: https://al1brn.github.io/geonodes/

theme:
  name: material
  features:
    - content.code.copy  

nav:
  - Home: index.md

  - Getting Started:
    - Hello World: getting_started/hello_world.md
    - Installation: getting_started/installation.md
    - Overview: getting_started/overview.md
    - Data Classes: getting_started/data_classes.md
    - Naming Conventions: getting_started/naming.md
    - Modifiers & Groups: getting_started/modifiers_groups.md
    - Creating Sockets: getting_started/creating_sockets.md
    - Linking Sockets: getting_started/linking_sockets.md
    - Zones: getting_started/zones.md
    - Doing maths: getting_started/math.md
    - Shaders: getting_started/shaders.md


  - API:
    - Overview: api/index.md
    - Trees:
        - GeoNodes: api/geonodes.md
        - ShaderNodes: api/shadernodes.md
        - Layout: api/layout.md
        - Panel: api/panel.md
        - Break: api/break.md
        - Tree: api/tree.md

    - Geometry Sockets:
        - Geometry : api/geometry.md
        - Mesh: api/mesh.md
        - Curve: api/curve.md
        - Instances: api/instances.md
        - Cloud: api/cloud.md
        - Volume: api/volume.md
        - Grease Pencil: api/grease_pencil.md

    - Other Sockets:
        - Socket: api/socket.md
        - Boolean: api/boolean.md
        - Bundle: api/bundle.md
        - Closure: api/closure.md
        - Collection : api/collection.md
        - Color: api/color.md
        - Float: api/float.md
        - Font: api/font.md
        - Image : api/image.md
        - Integer: api/integer.md
        - Material : api/material.md
        - Matrix: api/matrix.md
        - Menu: api/menu.md
        - Object : api/object.md
        - Rotation: api/rotation.md
        - String: api/string.md
        - Vector: api/vector.md

    - Nodes:
        - Group: api/group.md
        - G: api/g.md
        - Node: api/node.md

    - Domains:
        - Vertex: api/vertex.md
        - Edge: api/edge.md
        - Face: api/face.md
        - Corner: api/corner.md
        - SplinePoint: api/spline_point.md
        - Spline: api/spline.md
        - CloudPoint: api/cloud_point.md
        - Instance: api/instance.md
        - Layer: api/layer.md

    - Utilities:
        - gnmath module: api/gnmath.md
        - nd module: api/nd.md
        - snd module: api/snd.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences  
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: false  

hooks:
  - mkdocs_hooks.py
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            docstring_style: numpy
            inherited_members: true
            show_signature: true
            merge_init_into_class: false
            filters:
              - "!^__slots__$"