"""
This file is part of the geonodes distribution (https://github.com/al1brn/geonodes).
Copyright (c) 2025 Alain Bernard.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

$ DOC hidden

-----------------------------------------------------
Scripting Geometry Nodes
-----------------------------------------------------

module : constants
------------------
- declare global constants

updates
-------
- creation : 2024/07/23
- update :   2024/09/04
- update :   2025/01/12
"""

__author__ = "Alain Bernard"
__email__  = "lesideesfroides@gmail.com"
__copyright__ = "Copyright (c) 2025, Alain Bernard"
__license__ = "GNU GPL V3"
__version__ = "3.0.0"
__blender_version__ = "4.3.0"


# ====================================================================================================
# Class names from socket type

CLASS_NAMES = {
    'VALUE'         : 'Float',
    'INT'           : 'Integer',
    'BOOLEAN'       : 'Boolean',
    'VECTOR'        : 'Vector',
    'ROTATION'      : 'Rotation',
    'MATRIX'        : 'Matrix',
    'STRING'        : 'String',
    'MENU'          : 'Menu',
    'RGBA'          : 'Color',
    'OBJECT'        : 'Object',
    'IMAGE'         : 'Image',
    'GEOMETRY'      : 'Geometry',
    'COLLECTION'    : 'Collection',
    'MATERIAL'      : 'Material',
    'TEXTURE'       : 'Texture',

    'SHADER'        : 'Shader',
}

ATTRIBUTE_CLASSES = ['Boolean', 'Integer', 'Float', 'Vector', 'Color', 'Matrix', 'Rotation']

GEOMETRY_CLASSES = ['Geometry', 'Mesh', 'Curve', 'Cloud', 'Instances', 'Volume', 'GrasePencil']
DOMAIN_CLASSES   = ['Domain', 'Point', 'Vertex', 'CloudPoint', 'SplinePoint', 'Face', 'Edge', 'Corner', 'Spline', 'Layer', 'Instance']


# =============================================================================================================================
# Sockets dictionary
#
# Generated by node_explore.build_sockets_dict
#
# Blender version: 4.3.0
# Sockets: ['STRING', 'BOOLEAN', 'MATERIAL', 'VECTOR', 'INT', 'MENU', 'COLLECTION', 'GEOMETRY', 'TEXTURE', 'VALUE', 'RGBA', 'OBJECT', 'ROTATION', 'MATRIX', 'IMAGE', 'SHADER']

SOCKETS_DICT = {
    'BOOLEAN': {'GeometryNodeTree': True,
                'ShaderNodeTree': True,
                'class_name': 'Boolean',
                'nodesocket': 'NodeSocketBool',
                'short': 'Bool',
                'subtypes': []},
 'COLLECTION': {'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Collection',
                'nodesocket': 'NodeSocketCollection',
                'short': 'Collection',
                'subtypes': []},
 'GEOMETRY': {' GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Geometry',
                'nodesocket': 'NodeSocketGeometry',
                'short': 'Geometry',
                'subtypes': []},
 'IMAGE': {     'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Image',
                'nodesocket': 'NodeSocketImage',
                'short': 'Image',
                'subtypes': []},
 'INT': {       'GeometryNodeTree': True,
                'ShaderNodeTree': True,
                'class_name': 'Integer',
                'nodesocket': 'NodeSocketInt',
                'short': 'Int',
                'subtypes': ['NONE', 'PERCENTAGE', 'FACTOR']},
 'MATERIAL': {  'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Material',
                'nodesocket': 'NodeSocketMaterial',
                'short': 'Material',
                'subtypes': []},
 'MATRIX': {    'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Matrix',
                'nodesocket': 'NodeSocketMatrix',
                'short': 'Matrix',
                'subtypes': []},
 'MENU': {      'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Menu',
                'nodesocket': 'NodeSocketMenu',
                'short': 'Menu',
                'subtypes': []},
 'OBJECT': {    'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Object',
                'nodesocket': 'NodeSocketObject',
                'short': 'Object',
                'subtypes': []},
 'RGBA': {      'GeometryNodeTree': True,
                'ShaderNodeTree': True,
                'class_name': 'Color',
                'nodesocket': 'NodeSocketColor',
                'short': 'Color',
                'subtypes': []},
 'ROTATION': {  'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Rotation',
                'nodesocket': 'NodeSocketRotation',
                'short': 'Rotation',
                'subtypes': []},
 'SHADER': {    'GeometryNodeTree': False,
                'ShaderNodeTree': True,
                'class_name': 'Shader',
                'nodesocket': 'NodeSocketShader',
                'short': 'Shader',
                'subtypes': []},
 'STRING': {    'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'String',
                'nodesocket': 'NodeSocketString',
                'short': 'String',
                'subtypes': ['NONE', 'FILE_PATH']},
 'TEXTURE': {   'GeometryNodeTree': True,
                'ShaderNodeTree': False,
                'class_name': 'Texture',
                'nodesocket': 'NodeSocketTexture',
                'short': 'Texture',
                'subtypes': []},
 'VALUE': {     'GeometryNodeTree': True,
                'ShaderNodeTree': True,
                'class_name': 'Float',
                'nodesocket': 'NodeSocketFloat',
                'short': 'Float',
                'subtypes': ['NONE',
                             'PERCENTAGE',
                             'FACTOR',
                             'ANGLE',
                             'TIME',
                             'TIME_ABSOLUTE',
                             'DISTANCE',
                             'WAVELENGTH',
                             'COLOR_TEMPERATURE',
                             'FREQUENCY']},
 'VECTOR': {    'GeometryNodeTree': True,
                'ShaderNodeTree': True,
                'class_name': 'Vector',
                'nodesocket': 'NodeSocketVector',
                'short': 'Vector',
                'subtypes': ['NONE',
                             'TRANSLATION',
                             'DIRECTION',
                             'VELOCITY',
                             'ACCELERATION',
                             'EULER',
                             'XYZ']},
}

# ====================================================================================================
# Interface socket possible properties

INTERFACE_SOCKET_PROPERTIES = {
    'description'               : 'tip',
    'default_attribute_name'    : 'default_attribute',
    'subtype'                   : 'subtype',
    'default_value'             : 'default_value',
    'min_value'                 : 'min',
    'max_value'                 : 'max',
    'default_input'             : 'default_input',
    'hide_value'                : 'hide_value',
    'hide_in_modifier'          : 'hide_in_modifier',
    'force_non_field'           : 'single_value',
    'layer_selection_field'     : 'layer_selection',
}

# ====================================================================================================
# Correspondance between NodeSocket.type and type(NodeSocket)
# This list is automatically built from Blender with
# blendertree.gen_SOCKET_TYPES(tree_type)

SOCKET_TYPES = {
    'BOOLEAN':      ['NodeSocketBool'],
    'COLLECTION':   ['NodeSocketCollection'],
    'CUSTOM':       ['NodeSocketVirtual'],
    'GEOMETRY':     ['NodeSocketGeometry'],
    'IMAGE':        ['NodeSocketImage'],
    'INT':          ['NodeSocketInt',
                     'NodeSocketIntPercentage',
                     'NodeSocketIntFactor'],

    'MATERIAL':     ['NodeSocketMaterial'],
    'MATRIX':       ['NodeSocketMatrix'],
    'MENU':         ['NodeSocketMenu'],
    'OBJECT':       ['NodeSocketObject'],
    'RGBA':         ['NodeSocketColor'],
    'ROTATION':     ['NodeSocketRotation'],
    'STRING':       ['NodeSocketString',
                     'NodeSocketStringFilePath'],
    'TEXTURE':      ['NodeSocketTexture'],

    'VALUE':        ['NodeSocketFloat',
                     'NodeSocketFloatFactor',
                     'NodeSocketFloatAngle',
                     'NodeSocketFloatDistance'],

    'VECTOR':       ['NodeSocketVector',
                     'NodeSocketVectorTranslation',
                     'NodeSocketVectorDirection',
                     'NodeSocketVectorVelocity',
                     'NodeSocketVectorAcceleration',
                     'NodeSocketVectorEuler',
                     'NodeSocketVectorXYZ'],
    }


SOCKET_SUBTYPES = {
    'NodeSocketBool'                : ('NodeSocketBool',        None),
    'NodeSocketCollection'          : ('NodeSocketCollection',  None),
    'NodeSocketVirtual'             : ('NodeSocketVirtual',     None),
    'NodeSocketGeometry'            : ('NodeSocketGeometry',    None),
    'NodeSocketImage'               : ('NodeSocketImage',       None),
    'NodeSocketTexture'             : ('NodeSocketTexture',     None),

    'NodeSocketInt'                 : ('NodeSocketInt',         'NONE'),
    'NodeSocketIntPercentage'       : ('NodeSocketInt',         'PERCENTAGE'),
    'NodeSocketIntFactor'           : ('NodeSocketInt',         'FACTOR'),

    'NodeSocketMaterial'            : ('NodeSocketMaterial',    None),
    'NodeSocketMatrix'              : ('NodeSocketMatrix',      None),
    'NodeSocketMenu'                : ('NodeSocketMenu',        None),
    'NodeSocketObject'              : ('NodeSocketObject',      None),
    'NodeSocketColor'               : ('NodeSocketColor',       None),
    'NodeSocketRotation'            : ('NodeSocketRotation',    None),
    'NodeSocketString'              : ('NodeSocketString',      'NONE'),
    'NodeSocketStringFilePath'      : ('NodeSocketString',      'FILE_PATH'),

    'NodeSocketFloat'               : ('NodeSocketFloat',       'NONE'),
    'NodeSocketFloatPercentage'     : ('NodeSocketFloat',       'PERCENTAGE'),
    'NodeSocketFloatFactor'         : ('NodeSocketFloat',       'FACTOR'),
    'NodeSocketFloatAngle'          : ('NodeSocketFloat',       'ANGLE'),
    'NodeSocketFloatTime'           : ('NodeSocketFloat',       'TIME'),
    'NodeSocketFloatTimeAbsolute'   : ('NodeSocketFloat',       'TIME_ABSOLUTE'),
    'NodeSocketFloatDistance'       : ('NodeSocketFloat',       'DISTANCE'),
    'NodeSocketFloatWavelength'     : ('NodeSocketFloat',       'WAVELENGTH'),
    'NodeSocketFloatColorTemperature': ('NodeSocketFloat',      'COLOR_TEMPERATURE'),
    'NodeSocketFloatFrequency'      : ('NodeSocketFloat',        'FREQUENCY'),

    'NodeSocketVector'              : ('NodeSocketVector',      'NONE'),
    'NodeSocketVectorTranslation'   : ('NodeSocketVector',      'TRANSLATION'),
    'NodeSocketVectorDirection'     : ('NodeSocketVector',      'DIRECTION'),
    'NodeSocketVectorVelocity'      : ('NodeSocketVector',      'VELOCITY'),
    'NodeSocketVectorAcceleration'  : ('NodeSocketVector',      'ACCELERATION'),
    'NodeSocketVectorEuler'         : ('NodeSocketVector',      'EULER'),
    'NodeSocketVectorXYZ'           : ('NodeSocketVector',      'XYZ'),
}


DATA_TYPES = {
    'VALUE'      : 'FLOAT',
    'INT'        : 'INT',
    'VECTOR'     : 'FLOAT_VECTOR',
    'RGBA'       : 'FLOAT_COLOR',
    'BOOLEAN'    : 'BOOLEAN',
    'MATRIX'     : 'FLOAT4X4',
    'ROTATION'   : 'QUATERNION',

    'BYTE_COLOR' : 'BYTE_COLOR',
    'FLOAT2'     : 'FLOAT2',
    'INT8'       : 'INT8',
}

INPUT_TYPES = {
    'FLOAT'         : 'FLOAT',
    'VALUE'         : 'FLOAT',
    'INT'           : 'INT',
    'BOOLEAN'       : 'BOOLEAN',
    'VECTOR'        : 'VECTOR',
    'ROTATION'      : 'ROTATION',
    'MATRIX'        : 'MATRIX',
    'STRING'        : 'STRING',
    'MENU'          : 'MENU',
    'RGBA'          : 'RGBA',
    'OBJECT'        : 'OBJECT',
    'IMAGE'         : 'IMAGE',
    'GEOMETRY'      : 'GEOMETRY',
    'COLLECTION'    : 'COLLECTION',
    'MATERIAL'      : 'MATERIAL',

    'SHADER'        : 'SHADER',
}

# =============================================================================================================================
# Valid types

VALID_SOCKET_TYPES = {
    'GeometryNodeTree': ['BOOLEAN', 'COLLECTION', 'CUSTOM', 'GEOMETRY', 'IMAGE', 'INT', 'MATERIAL', 'MATRIX', 'MENU',
                         'OBJECT', 'RGBA', 'ROTATION', 'STRING', 'VALUE', 'VECTOR'],
    'ShaderNodeTree': ['CUSTOM', 'RGBA', 'ROTATION', 'SHADER', 'STRING', 'VALUE', 'VECTOR'],
}

# =============================================================================================================================
# Array type combination

ARRAY_TYPES = {
    'VECTOR'  : {'shape': (3,),  'combine': 'Combine XYZ',    'init': 'Vector',   'param': 'vector'},
    'ROTATION': {'shape': (3,),  'combine': 'Combine XYZ',    'init': 'Rotation', 'param': 'rotation'},
    'RGBA'    : {'shape': (4,),  'combine': 'Combine Color',  'init': 'Color',    'param': 'color'},
    'MATRIX'  : {'shape': (16,), 'combine': 'Combine Matrix', 'init': None},
}

# =============================================================================================================================

TOOL_ONLY = (
    '3D Cursor',
    'Mouse Position',
    'Viewport Transform',
    'Active Element',
    'Selection',
    'Set Selection',
    'Face Set',
    'Set Face Set',
)

MODIFIER_ONLY = (
    'Simulation Input',
    'Viewer',
)

# =============================================================================================================================
# Node bl_idname from node name
#
# Generated by node_explore.build_node_names_dict
#
# Blender version: 4.3.0
# Total: GeometryNodeTree: 268, ShaderNodeTree: 99

NODE_NAMES = {
	'GeometryNodeTree' : {
		'Align Rotation to Vector'     : 'FunctionNodeAlignRotationToVector',
		'Axes to Rotation'             : 'FunctionNodeAxesToRotation',
		'Axis Angle to Rotation'       : 'FunctionNodeAxisAngleToRotation',
		'Boolean Math'                 : 'FunctionNodeBooleanMath',
		'Combine Color'                : 'FunctionNodeCombineColor',
		'Combine Matrix'               : 'FunctionNodeCombineMatrix',
		'Combine Transform'            : 'FunctionNodeCombineTransform',
		'Compare'                      : 'FunctionNodeCompare',
		'Euler to Rotation'            : 'FunctionNodeEulerToRotation',
		'Float to Integer'             : 'FunctionNodeFloatToInt',
		'Hash Value'                   : 'FunctionNodeHashValue',
		'Boolean'                      : 'FunctionNodeInputBool',
		'Color'                        : 'FunctionNodeInputColor',
		'Integer'                      : 'FunctionNodeInputInt',
		'Rotation'                     : 'FunctionNodeInputRotation',
		'Special Characters'           : 'FunctionNodeInputSpecialCharacters',
		'String'                       : 'FunctionNodeInputString',
		'Vector'                       : 'FunctionNodeInputVector',
		'Integer Math'                 : 'FunctionNodeIntegerMath',
		'Invert Matrix'                : 'FunctionNodeInvertMatrix',
		'Invert Rotation'              : 'FunctionNodeInvertRotation',
		'Matrix Determinant'           : 'FunctionNodeMatrixDeterminant',
		'Multiply Matrices'            : 'FunctionNodeMatrixMultiply',
		'Project Point'                : 'FunctionNodeProjectPoint',
		'Quaternion to Rotation'       : 'FunctionNodeQuaternionToRotation',
		'Random Value'                 : 'FunctionNodeRandomValue',
		'Replace String'               : 'FunctionNodeReplaceString',
		'Rotate Rotation'              : 'FunctionNodeRotateRotation',
		'Rotate Vector'                : 'FunctionNodeRotateVector',
		'Rotation to Axis Angle'       : 'FunctionNodeRotationToAxisAngle',
		'Rotation to Euler'            : 'FunctionNodeRotationToEuler',
		'Rotation to Quaternion'       : 'FunctionNodeRotationToQuaternion',
		'Separate Color'               : 'FunctionNodeSeparateColor',
		'Separate Matrix'              : 'FunctionNodeSeparateMatrix',
		'Separate Transform'           : 'FunctionNodeSeparateTransform',
		'Slice String'                 : 'FunctionNodeSliceString',
		'String Length'                : 'FunctionNodeStringLength',
		'Transform Direction'          : 'FunctionNodeTransformDirection',
		'Transform Point'              : 'FunctionNodeTransformPoint',
		'Transpose Matrix'             : 'FunctionNodeTransposeMatrix',
		'Value to String'              : 'FunctionNodeValueToString',
		'Accumulate Field'             : 'GeometryNodeAccumulateField',
		'Domain Size'                  : 'GeometryNodeAttributeDomainSize',
		'Attribute Statistic'          : 'GeometryNodeAttributeStatistic',
		'Bake'                         : 'GeometryNodeBake',
		'Blur Attribute'               : 'GeometryNodeBlurAttribute',
		'Bounding Box'                 : 'GeometryNodeBoundBox',
		'Capture Attribute'            : 'GeometryNodeCaptureAttribute',
		'Collection Info'              : 'GeometryNodeCollectionInfo',
		'Convex Hull'                  : 'GeometryNodeConvexHull',
		'Corners of Edge'              : 'GeometryNodeCornersOfEdge',
		'Corners of Face'              : 'GeometryNodeCornersOfFace',
		'Corners of Vertex'            : 'GeometryNodeCornersOfVertex',
		'Arc'                          : 'GeometryNodeCurveArc',
		'Endpoint Selection'           : 'GeometryNodeCurveEndpointSelection',
		'Handle Type Selection'        : 'GeometryNodeCurveHandleTypeSelection',
		'Curve Length'                 : 'GeometryNodeCurveLength',
		'Curve of Point'               : 'GeometryNodeCurveOfPoint',
		'Bézier Segment'               : 'GeometryNodeCurvePrimitiveBezierSegment',
		'Curve Circle'                 : 'GeometryNodeCurvePrimitiveCircle',
		'Curve Line'                   : 'GeometryNodeCurvePrimitiveLine',
		'Quadrilateral'                : 'GeometryNodeCurvePrimitiveQuadrilateral',
		'Quadratic Bézier'             : 'GeometryNodeCurveQuadraticBezier',
		'Set Handle Type'              : 'GeometryNodeCurveSetHandles',
		'Spiral'                       : 'GeometryNodeCurveSpiral',
		'Set Spline Type'              : 'GeometryNodeCurveSplineType',
		'Star'                         : 'GeometryNodeCurveStar',
		'Curve to Mesh'                : 'GeometryNodeCurveToMesh',
		'Curve to Points'              : 'GeometryNodeCurveToPoints',
		'Curves to Grease Pencil'      : 'GeometryNodeCurvesToGreasePencil',
		'Deform Curves on Surface'     : 'GeometryNodeDeformCurvesOnSurface',
		'Delete Geometry'              : 'GeometryNodeDeleteGeometry',
		'Distribute Points in Grid'    : 'GeometryNodeDistributePointsInGrid',
		'Distribute Points in Volume'  : 'GeometryNodeDistributePointsInVolume',
		'Distribute Points on Faces'   : 'GeometryNodeDistributePointsOnFaces',
		'Dual Mesh'                    : 'GeometryNodeDualMesh',
		'Duplicate Elements'           : 'GeometryNodeDuplicateElements',
		'Edge Paths to Curves'         : 'GeometryNodeEdgePathsToCurves',
		'Edge Paths to Selection'      : 'GeometryNodeEdgePathsToSelection',
		'Edges of Corner'              : 'GeometryNodeEdgesOfCorner',
		'Edges of Vertex'              : 'GeometryNodeEdgesOfVertex',
		'Edges to Face Groups'         : 'GeometryNodeEdgesToFaceGroups',
		'Extrude Mesh'                 : 'GeometryNodeExtrudeMesh',
		'Face of Corner'               : 'GeometryNodeFaceOfCorner',
		'Evaluate at Index'            : 'GeometryNodeFieldAtIndex',
		'Evaluate on Domain'           : 'GeometryNodeFieldOnDomain',
		'Fill Curve'                   : 'GeometryNodeFillCurve',
		'Fillet Curve'                 : 'GeometryNodeFilletCurve',
		'Flip Faces'                   : 'GeometryNodeFlipFaces',
		'For Each Geometry Element Input' : 'GeometryNodeForeachGeometryElementInput',
		'For Each Geometry Element Output' : 'GeometryNodeForeachGeometryElementOutput',
		'Geometry to Instance'         : 'GeometryNodeGeometryToInstance',
		'Get Named Grid'               : 'GeometryNodeGetNamedGrid',
		'Dial Gizmo'                   : 'GeometryNodeGizmoDial',
		'Linear Gizmo'                 : 'GeometryNodeGizmoLinear',
		'Transform Gizmo'              : 'GeometryNodeGizmoTransform',
		'Grease Pencil to Curves'      : 'GeometryNodeGreasePencilToCurves',
		'Grid to Mesh'                 : 'GeometryNodeGridToMesh',
		'Group'                        : 'GeometryNodeGroup',
		'Image Info'                   : 'GeometryNodeImageInfo',
		'Image Texture'                : 'GeometryNodeImageTexture',
		'Import OBJ'                   : 'GeometryNodeImportOBJ',
		'Import PLY'                   : 'GeometryNodeImportPLY',
		'Import STL'                   : 'GeometryNodeImportSTL',
		'Index of Nearest'             : 'GeometryNodeIndexOfNearest',
		'Index Switch'                 : 'GeometryNodeIndexSwitch',
		'Active Camera'                : 'GeometryNodeInputActiveCamera',
		'Curve Handle Positions'       : 'GeometryNodeInputCurveHandlePositions',
		'Curve Tilt'                   : 'GeometryNodeInputCurveTilt',
		'Is Edge Smooth'               : 'GeometryNodeInputEdgeSmooth',
		'ID'                           : 'GeometryNodeInputID',
		'Image'                        : 'GeometryNodeInputImage',
		'Index'                        : 'GeometryNodeInputIndex',
		'Instance Rotation'            : 'GeometryNodeInputInstanceRotation',
		'Instance Scale'               : 'GeometryNodeInputInstanceScale',
		'Material'                     : 'GeometryNodeInputMaterial',
		'Material Index'               : 'GeometryNodeInputMaterialIndex',
		'Edge Angle'                   : 'GeometryNodeInputMeshEdgeAngle',
		'Edge Neighbors'               : 'GeometryNodeInputMeshEdgeNeighbors',
		'Edge Vertices'                : 'GeometryNodeInputMeshEdgeVertices',
		'Face Area'                    : 'GeometryNodeInputMeshFaceArea',
		'Is Face Planar'               : 'GeometryNodeInputMeshFaceIsPlanar',
		'Face Neighbors'               : 'GeometryNodeInputMeshFaceNeighbors',
		'Mesh Island'                  : 'GeometryNodeInputMeshIsland',
		'Vertex Neighbors'             : 'GeometryNodeInputMeshVertexNeighbors',
		'Named Attribute'              : 'GeometryNodeInputNamedAttribute',
		'Named Layer Selection'        : 'GeometryNodeInputNamedLayerSelection',
		'Normal'                       : 'GeometryNodeInputNormal',
		'Position'                     : 'GeometryNodeInputPosition',
		'Radius'                       : 'GeometryNodeInputRadius',
		'Scene Time'                   : 'GeometryNodeInputSceneTime',
		'Is Face Smooth'               : 'GeometryNodeInputShadeSmooth',
		'Shortest Edge Paths'          : 'GeometryNodeInputShortestEdgePaths',
		'Is Spline Cyclic'             : 'GeometryNodeInputSplineCyclic',
		'Spline Resolution'            : 'GeometryNodeInputSplineResolution',
		'Curve Tangent'                : 'GeometryNodeInputTangent',
		'Instance on Points'           : 'GeometryNodeInstanceOnPoints',
		'Instance Transform'           : 'GeometryNodeInstanceTransform',
		'Instances to Points'          : 'GeometryNodeInstancesToPoints',
		'Interpolate Curves'           : 'GeometryNodeInterpolateCurves',
		'Is Viewport'                  : 'GeometryNodeIsViewport',
		'Join Geometry'                : 'GeometryNodeJoinGeometry',
		'Material Selection'           : 'GeometryNodeMaterialSelection',
		'Menu Switch'                  : 'GeometryNodeMenuSwitch',
		'Merge by Distance'            : 'GeometryNodeMergeByDistance',
		'Merge Layers'                 : 'GeometryNodeMergeLayers',
		'Mesh Boolean'                 : 'GeometryNodeMeshBoolean',
		'Mesh Circle'                  : 'GeometryNodeMeshCircle',
		'Cone'                         : 'GeometryNodeMeshCone',
		'Cube'                         : 'GeometryNodeMeshCube',
		'Cylinder'                     : 'GeometryNodeMeshCylinder',
		'Face Group Boundaries'        : 'GeometryNodeMeshFaceSetBoundaries',
		'Grid'                         : 'GeometryNodeMeshGrid',
		'Ico Sphere'                   : 'GeometryNodeMeshIcoSphere',
		'Mesh Line'                    : 'GeometryNodeMeshLine',
		'Mesh to Curve'                : 'GeometryNodeMeshToCurve',
		'Mesh to Density Grid'         : 'GeometryNodeMeshToDensityGrid',
		'Mesh to Points'               : 'GeometryNodeMeshToPoints',
		'Mesh to SDF Grid'             : 'GeometryNodeMeshToSDFGrid',
		'Mesh to Volume'               : 'GeometryNodeMeshToVolume',
		'UV Sphere'                    : 'GeometryNodeMeshUVSphere',
		'Object Info'                  : 'GeometryNodeObjectInfo',
		'Offset Corner in Face'        : 'GeometryNodeOffsetCornerInFace',
		'Offset Point in Curve'        : 'GeometryNodeOffsetPointInCurve',
		'Points'                       : 'GeometryNodePoints',
		'Points of Curve'              : 'GeometryNodePointsOfCurve',
		'Points to Curves'             : 'GeometryNodePointsToCurves',
		'Points to SDF Grid'           : 'GeometryNodePointsToSDFGrid',
		'Points to Vertices'           : 'GeometryNodePointsToVertices',
		'Points to Volume'             : 'GeometryNodePointsToVolume',
		'Geometry Proximity'           : 'GeometryNodeProximity',
		'Raycast'                      : 'GeometryNodeRaycast',
		'Realize Instances'            : 'GeometryNodeRealizeInstances',
		'Remove Named Attribute'       : 'GeometryNodeRemoveAttribute',
		'Repeat Input'                 : 'GeometryNodeRepeatInput',
		'Repeat Output'                : 'GeometryNodeRepeatOutput',
		'Replace Material'             : 'GeometryNodeReplaceMaterial',
		'Resample Curve'               : 'GeometryNodeResampleCurve',
		'Reverse Curve'                : 'GeometryNodeReverseCurve',
		'Rotate Instances'             : 'GeometryNodeRotateInstances',
		'SDF Grid Boolean'             : 'GeometryNodeSDFGridBoolean',
		'Sample Curve'                 : 'GeometryNodeSampleCurve',
		'Sample Grid'                  : 'GeometryNodeSampleGrid',
		'Sample Grid Index'            : 'GeometryNodeSampleGridIndex',
		'Sample Index'                 : 'GeometryNodeSampleIndex',
		'Sample Nearest'               : 'GeometryNodeSampleNearest',
		'Sample Nearest Surface'       : 'GeometryNodeSampleNearestSurface',
		'Sample UV Surface'            : 'GeometryNodeSampleUVSurface',
		'Scale Elements'               : 'GeometryNodeScaleElements',
		'Scale Instances'              : 'GeometryNodeScaleInstances',
		'Self Object'                  : 'GeometryNodeSelfObject',
		'Separate Components'          : 'GeometryNodeSeparateComponents',
		'Separate Geometry'            : 'GeometryNodeSeparateGeometry',
		'Set Handle Positions'         : 'GeometryNodeSetCurveHandlePositions',
		'Set Curve Normal'             : 'GeometryNodeSetCurveNormal',
		'Set Curve Radius'             : 'GeometryNodeSetCurveRadius',
		'Set Curve Tilt'               : 'GeometryNodeSetCurveTilt',
		'Set Geometry Name'            : 'GeometryNodeSetGeometryName',
		'Set ID'                       : 'GeometryNodeSetID',
		'Set Instance Transform'       : 'GeometryNodeSetInstanceTransform',
		'Set Material'                 : 'GeometryNodeSetMaterial',
		'Set Material Index'           : 'GeometryNodeSetMaterialIndex',
		'Set Point Radius'             : 'GeometryNodeSetPointRadius',
		'Set Position'                 : 'GeometryNodeSetPosition',
		'Set Shade Smooth'             : 'GeometryNodeSetShadeSmooth',
		'Set Spline Cyclic'            : 'GeometryNodeSetSplineCyclic',
		'Set Spline Resolution'        : 'GeometryNodeSetSplineResolution',
		'Simulation Input'             : 'GeometryNodeSimulationInput',
		'Simulation Output'            : 'GeometryNodeSimulationOutput',
		'Sort Elements'                : 'GeometryNodeSortElements',
		'Spline Length'                : 'GeometryNodeSplineLength',
		'Spline Parameter'             : 'GeometryNodeSplineParameter',
		'Split Edges'                  : 'GeometryNodeSplitEdges',
		'Split to Instances'           : 'GeometryNodeSplitToInstances',
		'Store Named Attribute'        : 'GeometryNodeStoreNamedAttribute',
		'Store Named Grid'             : 'GeometryNodeStoreNamedGrid',
		'Join Strings'                 : 'GeometryNodeStringJoin',
		'String to Curves'             : 'GeometryNodeStringToCurves',
		'Subdivide Curve'              : 'GeometryNodeSubdivideCurve',
		'Subdivide Mesh'               : 'GeometryNodeSubdivideMesh',
		'Subdivision Surface'          : 'GeometryNodeSubdivisionSurface',
		'Switch'                       : 'GeometryNodeSwitch',
		'3D Cursor'                    : 'GeometryNodeTool3DCursor',
		'Active Element'               : 'GeometryNodeToolActiveElement',
		'Face Set'                     : 'GeometryNodeToolFaceSet',
		'Mouse Position'               : 'GeometryNodeToolMousePosition',
		'Selection'                    : 'GeometryNodeToolSelection',
		'Set Face Set'                 : 'GeometryNodeToolSetFaceSet',
		'Set Selection'                : 'GeometryNodeToolSetSelection',
		'Transform Geometry'           : 'GeometryNodeTransform',
		'Translate Instances'          : 'GeometryNodeTranslateInstances',
		'Triangulate'                  : 'GeometryNodeTriangulate',
		'Trim Curve'                   : 'GeometryNodeTrimCurve',
		'Pack UV Islands'              : 'GeometryNodeUVPackIslands',
		'UV Unwrap'                    : 'GeometryNodeUVUnwrap',
		'Vertex of Corner'             : 'GeometryNodeVertexOfCorner',
		'Viewer'                       : 'GeometryNodeViewer',
		'Viewport Transform'           : 'GeometryNodeViewportTransform',
		'Volume Cube'                  : 'GeometryNodeVolumeCube',
		'Volume to Mesh'               : 'GeometryNodeVolumeToMesh',
		'Warning'                      : 'GeometryNodeWarning',
		'Frame'                        : 'NodeFrame',
		'Group Input'                  : 'NodeGroupInput',
		'Group Output'                 : 'NodeGroupOutput',
		'Reroute'                      : 'NodeReroute',
		'Blackbody'                    : 'ShaderNodeBlackbody',
		'Clamp'                        : 'ShaderNodeClamp',
		'Combine XYZ'                  : 'ShaderNodeCombineXYZ',
		'Float Curve'                  : 'ShaderNodeFloatCurve',
		'Map Range'                    : 'ShaderNodeMapRange',
		'Math'                         : 'ShaderNodeMath',
		'Mix'                          : 'ShaderNodeMix',
		'RGB Curves'                   : 'ShaderNodeRGBCurve',
		'Separate XYZ'                 : 'ShaderNodeSeparateXYZ',
		'Brick Texture'                : 'ShaderNodeTexBrick',
		'Checker Texture'              : 'ShaderNodeTexChecker',
		'Gabor Texture'                : 'ShaderNodeTexGabor',
		'Gradient Texture'             : 'ShaderNodeTexGradient',
		'Magic Texture'                : 'ShaderNodeTexMagic',
		'Noise Texture'                : 'ShaderNodeTexNoise',
		'Voronoi Texture'              : 'ShaderNodeTexVoronoi',
		'Wave Texture'                 : 'ShaderNodeTexWave',
		'White Noise Texture'          : 'ShaderNodeTexWhiteNoise',
		'Color Ramp'                   : 'ShaderNodeValToRGB',
		'Value'                        : 'ShaderNodeValue',
		'Vector Curves'                : 'ShaderNodeVectorCurve',
		'Vector Math'                  : 'ShaderNodeVectorMath',
		'Vector Rotate'                : 'ShaderNodeVectorRotate',
	},
	'ShaderNodeTree' : {
		'Frame'                        : 'NodeFrame',
		'Group Input'                  : 'NodeGroupInput',
		'Group Output'                 : 'NodeGroupOutput',
		'Reroute'                      : 'NodeReroute',
		'Add Shader'                   : 'ShaderNodeAddShader',
		'Ambient Occlusion'            : 'ShaderNodeAmbientOcclusion',
		'Attribute'                    : 'ShaderNodeAttribute',
		'Background'                   : 'ShaderNodeBackground',
		'Bevel'                        : 'ShaderNodeBevel',
		'Blackbody'                    : 'ShaderNodeBlackbody',
		'Brightness/Contrast'          : 'ShaderNodeBrightContrast',
		'Glossy BSDF'                  : 'ShaderNodeBsdfAnisotropic',
		'Diffuse BSDF'                 : 'ShaderNodeBsdfDiffuse',
		'Glass BSDF'                   : 'ShaderNodeBsdfGlass',
		'Hair BSDF'                    : 'ShaderNodeBsdfHair',
		'Principled Hair BSDF'         : 'ShaderNodeBsdfHairPrincipled',
		'Metallic BSDF'                : 'ShaderNodeBsdfMetallic',
		'Principled BSDF'              : 'ShaderNodeBsdfPrincipled',
		'Ray Portal BSDF'              : 'ShaderNodeBsdfRayPortal',
		'Refraction BSDF'              : 'ShaderNodeBsdfRefraction',
		'Sheen BSDF'                   : 'ShaderNodeBsdfSheen',
		'Toon BSDF'                    : 'ShaderNodeBsdfToon',
		'Translucent BSDF'             : 'ShaderNodeBsdfTranslucent',
		'Transparent BSDF'             : 'ShaderNodeBsdfTransparent',
		'Bump'                         : 'ShaderNodeBump',
		'Camera Data'                  : 'ShaderNodeCameraData',
		'Clamp'                        : 'ShaderNodeClamp',
		'Combine Color'                : 'ShaderNodeCombineColor',
		'Combine XYZ'                  : 'ShaderNodeCombineXYZ',
		'Displacement'                 : 'ShaderNodeDisplacement',
		'Specular BSDF'                : 'ShaderNodeEeveeSpecular',
		'Emission'                     : 'ShaderNodeEmission',
		'Float Curve'                  : 'ShaderNodeFloatCurve',
		'Fresnel'                      : 'ShaderNodeFresnel',
		'Gamma'                        : 'ShaderNodeGamma',
		'Group'                        : 'ShaderNodeGroup',
		'Curves Info'                  : 'ShaderNodeHairInfo',
		'Holdout'                      : 'ShaderNodeHoldout',
		'Hue/Saturation/Value'         : 'ShaderNodeHueSaturation',
		'Invert Color'                 : 'ShaderNodeInvert',
		'Layer Weight'                 : 'ShaderNodeLayerWeight',
		'Light Falloff'                : 'ShaderNodeLightFalloff',
		'Light Path'                   : 'ShaderNodeLightPath',
		'Map Range'                    : 'ShaderNodeMapRange',
		'Mapping'                      : 'ShaderNodeMapping',
		'Math'                         : 'ShaderNodeMath',
		'Mix'                          : 'ShaderNodeMix',
		'Mix Shader'                   : 'ShaderNodeMixShader',
		'Geometry'                     : 'ShaderNodeNewGeometry',
		'Normal'                       : 'ShaderNodeNormal',
		'Normal Map'                   : 'ShaderNodeNormalMap',
		'Object Info'                  : 'ShaderNodeObjectInfo',
		'AOV Output'                   : 'ShaderNodeOutputAOV',
		'Light Output'                 : 'ShaderNodeOutputLight',
		'Line Style Output'            : 'ShaderNodeOutputLineStyle',
		'Material Output'              : 'ShaderNodeOutputMaterial',
		'World Output'                 : 'ShaderNodeOutputWorld',
		'Particle Info'                : 'ShaderNodeParticleInfo',
		'Point Info'                   : 'ShaderNodePointInfo',
		'RGB'                          : 'ShaderNodeRGB',
		'RGB Curves'                   : 'ShaderNodeRGBCurve',
		'RGB to BW'                    : 'ShaderNodeRGBToBW',
		'Script'                       : 'ShaderNodeScript',
		'Separate Color'               : 'ShaderNodeSeparateColor',
		'Separate XYZ'                 : 'ShaderNodeSeparateXYZ',
		'Shader to RGB'                : 'ShaderNodeShaderToRGB',
		'Subsurface Scattering'        : 'ShaderNodeSubsurfaceScattering',
		'Tangent'                      : 'ShaderNodeTangent',
		'Brick Texture'                : 'ShaderNodeTexBrick',
		'Checker Texture'              : 'ShaderNodeTexChecker',
		'Texture Coordinate'           : 'ShaderNodeTexCoord',
		'Environment Texture'          : 'ShaderNodeTexEnvironment',
		'Gabor Texture'                : 'ShaderNodeTexGabor',
		'Gradient Texture'             : 'ShaderNodeTexGradient',
		'IES Texture'                  : 'ShaderNodeTexIES',
		'Image Texture'                : 'ShaderNodeTexImage',
		'Magic Texture'                : 'ShaderNodeTexMagic',
		'Noise Texture'                : 'ShaderNodeTexNoise',
		'Point Density'                : 'ShaderNodeTexPointDensity',
		'Sky Texture'                  : 'ShaderNodeTexSky',
		'Voronoi Texture'              : 'ShaderNodeTexVoronoi',
		'Wave Texture'                 : 'ShaderNodeTexWave',
		'White Noise Texture'          : 'ShaderNodeTexWhiteNoise',
		'UV Along Stroke'              : 'ShaderNodeUVAlongStroke',
		'UV Map'                       : 'ShaderNodeUVMap',
		'Color Ramp'                   : 'ShaderNodeValToRGB',
		'Value'                        : 'ShaderNodeValue',
		'Vector Curves'                : 'ShaderNodeVectorCurve',
		'Vector Displacement'          : 'ShaderNodeVectorDisplacement',
		'Vector Math'                  : 'ShaderNodeVectorMath',
		'Vector Rotate'                : 'ShaderNodeVectorRotate',
		'Vector Transform'             : 'ShaderNodeVectorTransform',
		'Color Attribute'              : 'ShaderNodeVertexColor',
		'Volume Absorption'            : 'ShaderNodeVolumeAbsorption',
		'Volume Info'                  : 'ShaderNodeVolumeInfo',
		'Principled Volume'            : 'ShaderNodeVolumePrincipled',
		'Volume Scatter'               : 'ShaderNodeVolumeScatter',
		'Wavelength'                   : 'ShaderNodeWavelength',
		'Wireframe'                    : 'ShaderNodeWireframe',
	},
}

# ====================================================================================================
# Nodes enum params transco
# Blender version: (4, 3, 0)

# ----------------------------------------------------------------------------------------------------
# Node specific transco

SPEC_ENUM_PARAMS = {
    'Boolean Math': {
        'Equal'                   : 'XNOR',
        'Not Equal'               : 'XOR',
        'Subtract'                : 'NIMPLY',
    },
    'Compare': {
        'Less Equal'              : 'LESS_EQUAL',
        'Greater Equal'           : 'GREATER_EQUAL',
    },
    ('Math', 'Vector Math', 'Integer Math'): {
        'Add'                     : 'ADD',
        'Sub'                     : 'SUBTRACT',
        'Mult'                    : 'MULTIPLY',
        'Div'                     : 'DIVIDE',
        'Abs'                     : 'ABSOLUTE',
        'Min'                     : 'MINIMUM',
        'Max'                     : 'MAXIMUM',
        'Sign'                    : 'SIGN',
        'Mod'                     : 'MODULO',
        'GCD'                     : 'GCD',
        'LCM'                     : 'LCM',

        'Log'                     : 'LOGARITHM',
        'Exp'                     : 'EXPONENT',
        'Smooth Min'              : 'SMOOTH_MIN',             # ['Math']
        'Smooth Max'              : 'SMOOTH_MAX',             # ['Math']
         #'Trunc'                   : 'TRUNC',                  # ['Math'] # Homonym with 'Float to Integer' and 'String to Curve''
        'Fract'                   : 'FRACT',                  # ['Math']
        'Sin'                     : 'SINE',                   # ['Math', 'Vector Math']
        'Cos'                     : 'COSINE',                 # ['Math', 'Vector Math']
        'Tan'                     : 'TANGENT',                # ['Math', 'Vector Math']
        'Asin'                    : 'ARCSINE',                # ['Math']
        'Acos'                    : 'ARCCOSINE',              # ['Math']
        'Atan'                    : 'ARCTANGENT',             # ['Math']
        'Atan2'                   : 'ARCTAN2',                # ['Math']
        'Sinh'                    : 'SINH',                   # ['Math']
        'Cosh'                    : 'COSH',                   # ['Math']
        'Tanh'                    : 'TANH',                   # ['Math']
        'Radians'                 : 'RADIANS',                # ['Math']
        'Degrees'                 : 'DEGREES',                # ['Math']

        'Cross'                   : 'CROSS_PRODUCT',          # ['Vector Math']
        'Dot'                     : 'DOT_PRODUCT',            # ['Vector Math']

    },
    'Delete Geometry': {
        'Only Edges and Faces'    : 'EDGE_FACE',
        'Only Faces'              : 'ONLY_FACE',
    },
    'Distribute Points in Volume': {
        'Random'                  : 'DENSITY_RANDOM',
        'Grid'                    : 'DENSITY_GRID',
    },
    'Distribute Points in Grid' : {
        'Random'                  : 'DENSITY_RANDOM',
        'Grid'                    : 'DENSITY_GRID',
    },
    'Distribute Points on Faces' : {
        'Poisson Disk'            : 'POISSON',
    },
    ('Mesh Circle', 'Cone', 'Cylinder'): {
        'Triangles'               : 'TRIANGLE_FAN',
    },
    ('Mesh to Volume', 'Points to Volume', 'Volume to Mesh'): {
        'Amount'                  : 'VOXEL_AMOUNT',
        'Size'                    : 'VOXEL_SIZE',
    },
    'Subdivision Surface': {
        'All'                     : 'SMOOTH_ALL',
    },
    'Map Range': {
        'Stepped Linear'          : 'STEPPED',
    },
    'Image Texture': {
        'Linear'                  : 'Linear',
    },
    'Wave Texture': {
        'Sine'                    : 'SIN',
        'Triangles'               : 'TRI',
    },
}


# ----------------------------------------------------------------------------------------------------
# Node specific transco
#
# Generated by node_explore.build_user_enum_params

ENUM_PARAMS = {
    'X'                       : 'X',                      # ['Align Rotation to Vector', 'Align Rotation to Vector', 'Axes to Rotation', 'Axes to Rotation', 'Dial Gizmo', 'Linear Gizmo', 'Wave Texture', 'Wave Texture']
    'Y'                       : 'Y',                      # ['Align Rotation to Vector', 'Align Rotation to Vector', 'Axes to Rotation', 'Axes to Rotation', 'Dial Gizmo', 'Linear Gizmo', 'Wave Texture', 'Wave Texture']
    'Z'                       : 'Z',                      # ['Align Rotation to Vector', 'Align Rotation to Vector', 'Axes to Rotation', 'Axes to Rotation', 'Dial Gizmo', 'Linear Gizmo', 'Wave Texture', 'Wave Texture']
    'Auto'                    : 'AUTO',                   # ['Align Rotation to Vector', 'Handle Type Selection', 'Set Handle Type']
    'And'                     : 'AND',                    # ['Boolean Math']
    'Or'                      : 'OR',                     # ['Boolean Math']
    'Not'                     : 'NOT',                    # ['Boolean Math']
    'Nand'                    : 'NAND',                   # ['Boolean Math']
    'Nor'                     : 'NOR',                    # ['Boolean Math']
    'Xnor'                    : 'XNOR',                   # ['Boolean Math']
    'Xor'                     : 'XOR',                    # ['Boolean Math']
    'Imply'                   : 'IMPLY',                  # ['Boolean Math']
    'Nimply'                  : 'NIMPLY',                 # ['Boolean Math']
    'RGB'                     : 'RGB',                    # ['Combine Color', 'Separate Color']
    'HSV'                     : 'HSV',                    # ['Combine Color', 'Separate Color']
    'HSL'                     : 'HSL',                    # ['Combine Color', 'Separate Color']
    'Element'                 : 'ELEMENT',                # ['Compare']
    'Length'                  : 'LENGTH',                 # ['Compare', 'Curve to Points', 'Resample Curve', 'Sample Curve', 'Trim Curve', 'Vector Math']
    'Average'                 : 'AVERAGE',                # ['Compare']
    'Dot Product'             : 'DOT_PRODUCT',            # ['Compare', 'Vector Math']
    'Direction'               : 'DIRECTION',              # ['Compare', 'Curve Line']
    'Less Than'               : 'LESS_THAN',              # ['Compare', 'Math']
    'Less Than or Equal'      : 'LESS_EQUAL',             # ['Compare']
    'Greater Than'            : 'GREATER_THAN',           # ['Compare', 'Math']
    'Greater Than or Equal'   : 'GREATER_EQUAL',          # ['Compare']
    'Equal'                   : 'EQUAL',                  # ['Compare']
    'Not Equal'               : 'NOT_EQUAL',              # ['Compare']
    'Round'                   : 'ROUND',                  # ['Float to Integer', 'Math']
    'Floor'                   : 'FLOOR',                  # ['Float to Integer', 'Math', 'Vector Math']
    'Ceiling'                 : 'CEILING',                # ['Float to Integer']
    'Truncate'                : 'TRUNCATE',               # ['Float to Integer', 'String to Curves']
    'Add'                     : 'ADD',                    # ['Integer Math', 'Math', 'Mix', 'Vector Math']
    'Subtract'                : 'SUBTRACT',               # ['Integer Math', 'Math', 'Mix', 'Vector Math']
    'Multiply'                : 'MULTIPLY',               # ['Integer Math', 'Math', 'Mix', 'Vector Math']
    'Divide'                  : 'DIVIDE',                 # ['Integer Math', 'Math', 'Mix', 'Vector Math']
    'Multiply Add'            : 'MULTIPLY_ADD',           # ['Integer Math', 'Math', 'Vector Math']
    'Absolute'                : 'ABSOLUTE',               # ['Integer Math', 'Math', 'Vector Math']
    'Negate'                  : 'NEGATE',                 # ['Integer Math']
    'Power'                   : 'POWER',                  # ['Integer Math', 'Math']
    'Minimum'                 : 'MINIMUM',                # ['Integer Math', 'Math', 'Vector Math']
    'Maximum'                 : 'MAXIMUM',                # ['Integer Math', 'Math', 'Vector Math']
    'Sign'                    : 'SIGN',                   # ['Integer Math', 'Math']
    'Divide Round'            : 'DIVIDE_ROUND',           # ['Integer Math']
    'Divide Floor'            : 'DIVIDE_FLOOR',           # ['Integer Math']
    'Divide Ceil'             : 'DIVIDE_CEIL',            # ['Integer Math']
    'Floored Modulo'          : 'FLOORED_MODULO',         # ['Integer Math', 'Math']
    'Modulo'                  : 'MODULO',                 # ['Integer Math', 'Math', 'Vector Math']
    'Greatest Common Divisor' : 'GCD',                    # ['Integer Math']
    'Least Common Multiple'   : 'LCM',                    # ['Integer Math']
    'Global'                  : 'GLOBAL',                 # ['Rotate Rotation']
    'Local'                   : 'LOCAL',                  # ['Rotate Rotation']
    'Mesh'                    : 'MESH',                   # ['Domain Size']
    'Point Cloud'             : 'POINTCLOUD',             # ['Domain Size']
    'Curve'                   : 'CURVE',                  # ['Domain Size']
    'Instances'               : 'INSTANCES',              # ['Domain Size']
    'Grease Pencil'           : 'GREASEPENCIL',           # ['Domain Size']
    'Original'                : 'ORIGINAL',               # ['Collection Info', 'Object Info']
    'Relative'                : 'RELATIVE',               # ['Collection Info', 'Object Info']
    'Points'                  : 'POINTS',                 # ['Arc', 'Curve Circle', 'Curve Line', 'Quadrilateral', 'Geometry Proximity']
    'Radius'                  : 'RADIUS',                 # ['Arc', 'Curve Circle']
    'Free'                    : 'FREE',                   # ['Handle Type Selection', 'Set Handle Type', 'Set Curve Normal']
    'Vector'                  : 'VECTOR',                 # ['Handle Type Selection', 'Set Handle Type', 'Switch']
    'Align'                   : 'ALIGN',                  # ['Handle Type Selection', 'Set Handle Type']
    'Position'                : 'POSITION',               # ['Bézier Segment']
    'Offset'                  : 'OFFSET',                 # ['Bézier Segment', 'Mesh Line']
    'Rectangle'               : 'RECTANGLE',              # ['Quadrilateral']
    'Parallelogram'           : 'PARALLELOGRAM',          # ['Quadrilateral']
    'Trapezoid'               : 'TRAPEZOID',              # ['Quadrilateral']
    'Kite'                    : 'KITE',                   # ['Quadrilateral']
    'Catmull Rom'             : 'CATMULL_ROM',            # ['Set Spline Type']
    'Poly'                    : 'POLY',                   # ['Set Spline Type', 'Fillet Curve']
    'Bezier'                  : 'BEZIER',                 # ['Set Spline Type', 'Fillet Curve']
    'NURBS'                   : 'NURBS',                  # ['Set Spline Type']
    'Evaluated'               : 'EVALUATED',              # ['Curve to Points', 'Resample Curve']
    'Count'                   : 'COUNT',                  # ['Curve to Points', 'Resample Curve']
    'All'                     : 'ALL',                    # ['Delete Geometry', 'Merge by Distance', 'Subdivision Surface']
    'Edge_Face'               : 'EDGE_FACE',              # ['Delete Geometry']
    'Only_Face'               : 'ONLY_FACE',              # ['Delete Geometry']
    'Density_Random'          : 'DENSITY_RANDOM',         # ['Distribute Points in Grid', 'Distribute Points in Volume']
    'Density_Grid'            : 'DENSITY_GRID',           # ['Distribute Points in Grid', 'Distribute Points in Volume']
    'Random'                  : 'RANDOM',                 # ['Distribute Points on Faces']
    'Poisson'                 : 'POISSON',                # ['Distribute Points on Faces']
    'Vertices'                : 'VERTICES',               # ['Extrude Mesh', 'Mesh to Points']
    'Edges'                   : 'EDGES',                  # ['Extrude Mesh', 'Mesh to Points', 'Geometry Proximity']
    'Faces'                   : 'FACES',                  # ['Extrude Mesh', 'Mesh to Points', 'Geometry Proximity']
    'Triangles'               : 'TRIANGLES',              # ['Fill Curve']
    'N-gons'                  : 'NGONS',                  # ['Fill Curve']
    'Primary'                 : 'PRIMARY',                # ['Dial Gizmo', 'Linear Gizmo']
    'Secondary'               : 'SECONDARY',              # ['Dial Gizmo', 'Linear Gizmo']
    'Arrow'                   : 'ARROW',                  # ['Linear Gizmo']
    'Cross'                   : 'CROSS',                  # ['Linear Gizmo']
    'Box'                     : 'BOX',                    # ['Linear Gizmo']
    'Repeat'                  : 'REPEAT',                 # ['Image Texture']
    'Extend'                  : 'EXTEND',                 # ['Image Texture']
    'Clip'                    : 'CLIP',                   # ['Image Texture', 'Triangulate']
    'Mirror'                  : 'MIRROR',                 # ['Image Texture']
    'Linear'                  : 'LINEAR',                 # ['Map Range', 'Gradient Texture']
    'Closest'                 : 'Closest',                # ['Image Texture']
    'Cubic'                   : 'Cubic',                  # ['Image Texture']
    'Connected'               : 'CONNECTED',              # ['Merge by Distance']
    'By Name'                 : 'MERGE_BY_NAME',          # ['Merge Layers']
    'By Group ID'             : 'MERGE_BY_ID',            # ['Merge Layers']
    'Intersect'               : 'INTERSECT',              # ['Mesh Boolean', 'SDF Grid Boolean']
    'Union'                   : 'UNION',                  # ['Mesh Boolean', 'SDF Grid Boolean']
    'Difference'              : 'DIFFERENCE',             # ['Mesh Boolean', 'SDF Grid Boolean', 'Mix']
    'Exact'                   : 'EXACT',                  # ['Mesh Boolean', 'Remove Named Attribute']
    'Float'                   : 'FLOAT',                  # ['Mesh Boolean', 'Switch', 'Set Selection']
    'None'                    : 'NONE',                   # ['Mesh Circle', 'Cone', 'Cylinder', 'Subdivision Surface']
    'N-Gon'                   : 'NGON',                   # ['Mesh Circle', 'Cone', 'Cylinder']
    'Triangle_Fan'            : 'TRIANGLE_FAN',           # ['Mesh Circle', 'Cone', 'Cylinder']
    'Total'                   : 'TOTAL',                  # ['Mesh Line']
    'Resolution'              : 'RESOLUTION',             # ['Mesh Line']
    'End Points'              : 'END_POINTS',             # ['Mesh Line']
    'Corners'                 : 'CORNERS',                # ['Mesh to Points']
    'Voxel_Amount'            : 'VOXEL_AMOUNT',           # ['Mesh to Volume', 'Points to Volume', 'Volume to Mesh']
    'Voxel_Size'              : 'VOXEL_SIZE',             # ['Mesh to Volume', 'Points to Volume', 'Volume to Mesh']
    'Interpolated'            : 'INTERPOLATED',           # ['Raycast']
    'Nearest'                 : 'NEAREST',                # ['Raycast', 'Sample Grid']
    'Wildcard'                : 'WILDCARD',               # ['Remove Named Attribute']
    'Factor'                  : 'FACTOR',                 # ['Sample Curve', 'Trim Curve']
    'Trilinear'               : 'TRILINEAR',              # ['Sample Grid']
    'Triquadratic'            : 'TRIQUADRATIC',           # ['Sample Grid']
    'Uniform'                 : 'UNIFORM',                # ['Scale Elements', 'Mix']
    'Single Axis'             : 'SINGLE_AXIS',            # ['Scale Elements']
    'Left'                    : 'LEFT',                   # ['Set Handle Positions', 'String to Curves']
    'Right'                   : 'RIGHT',                  # ['Set Handle Positions', 'String to Curves']
    'Minimum Twist'           : 'MINIMUM_TWIST',          # ['Set Curve Normal']
    'Z Up'                    : 'Z_UP',                   # ['Set Curve Normal']
    'Center'                  : 'CENTER',                 # ['String to Curves']
    'Justify'                 : 'JUSTIFY',                # ['String to Curves']
    'Flush'                   : 'FLUSH',                  # ['String to Curves']
    'Top'                     : 'TOP',                    # ['String to Curves']
    'Top Baseline'            : 'TOP_BASELINE',           # ['String to Curves']
    'Middle'                  : 'MIDDLE',                 # ['String to Curves']
    'Bottom Baseline'         : 'BOTTOM_BASELINE',        # ['String to Curves']
    'Bottom'                  : 'BOTTOM',                 # ['String to Curves']
    'Overflow'                : 'OVERFLOW',               # ['String to Curves']
    'Scale To Fit'            : 'SCALE_TO_FIT',           # ['String to Curves']
    'Midpoint'                : 'MIDPOINT',               # ['String to Curves']
    'Top Left'                : 'TOP_LEFT',               # ['String to Curves']
    'Top Center'              : 'TOP_CENTER',             # ['String to Curves']
    'Top Right'               : 'TOP_RIGHT',              # ['String to Curves']
    'Bottom Left'             : 'BOTTOM_LEFT',            # ['String to Curves']
    'Bottom Center'           : 'BOTTOM_CENTER',          # ['String to Curves']
    'Bottom Right'            : 'BOTTOM_RIGHT',           # ['String to Curves']
    'Keep Corners'                   : 'PRESERVE_CORNERS',                       # ['Subdivision Surface', 'Subdivision Surface']
    'Keep Corners Junctions'         : 'PRESERVE_CORNERS_AND_JUNCTIONS',         # ['Subdivision Surface']
    'Keep Corners Junctions Concave' : 'PRESERVE_CORNERS_JUNCTIONS_AND_CONCAVE', # ['Subdivision Surface']
    'Keep Boundaries'                : 'PRESERVE_BOUNDARIES',                    # ['Subdivision Surface']
    'Smooth_All'                     : 'SMOOTH_ALL',                             # ['Subdivision Surface']
    'Boolean'                 : 'BOOLEAN',                # ['Set Selection']
    'Matrix'                  : 'MATRIX',                 # ['Transform Geometry']
    'Components'              : 'COMPONENTS',             # ['Transform Geometry']
    'Beauty'                  : 'BEAUTY',                 # ['Triangulate', 'Triangulate']
    'Fixed'                   : 'FIXED',                  # ['Triangulate']
    'Fixed Alternate'         : 'FIXED_ALTERNATE',        # ['Triangulate']
    'Shortest Diagonal'       : 'SHORTEST_DIAGONAL',      # ['Triangulate']
    'Longest Diagonal'        : 'LONGEST_DIAGONAL',       # ['Triangulate']
    'Angle Based'             : 'ANGLE_BASED',            # ['UV Unwrap']
    'Conformal'               : 'CONFORMAL',              # ['UV Unwrap']
    'Grid'                    : 'GRID',                   # ['Volume to Mesh']
    'Min Max'                 : 'MINMAX',                 # ['Clamp']
    'Range'                   : 'RANGE',                  # ['Clamp']
    'Stepped Linear'          : 'STEPPED',                # ['Map Range']
    'Smooth Step'             : 'SMOOTHSTEP',             # ['Map Range']
    'Smoother Step'           : 'SMOOTHERSTEP',           # ['Map Range']
    'Logarithm'               : 'LOGARITHM',              # ['Math']
    'Square Root'             : 'SQRT',                   # ['Math']
    'Inverse Square Root'     : 'INVERSE_SQRT',           # ['Math']
    'Exponent'                : 'EXPONENT',               # ['Math']
    'Compare'                 : 'COMPARE',                # ['Math']
    'Smooth Mininimum'        : 'SMOOTH_MIN',             # ['Math']
    'Smooth Maximum'          : 'SMOOTH_MAX',             # ['Math']
    'Ceil'                    : 'CEIL',                   # ['Math', 'Vector Math']
    'Trunc'                   : 'TRUNC',                  # ['Math']
    'Fraction'                : 'FRACT',                  # ['Math']
    'Wrap'                    : 'WRAP',                   # ['Math', 'Vector Math']
    'Snap'                    : 'SNAP',                   # ['Math', 'Vector Math']
    'Ping-Pong'               : 'PINGPONG',               # ['Math']
    'Sine'                    : 'SINE',                   # ['Math', 'Vector Math']
    'Cosine'                  : 'COSINE',                 # ['Math', 'Vector Math']
    'Tangent'                 : 'TANGENT',                # ['Math', 'Vector Math']
    'Arcsine'                 : 'ARCSINE',                # ['Math']
    'Arccosine'               : 'ARCCOSINE',              # ['Math']
    'Arctangent'              : 'ARCTANGENT',             # ['Math']
    'Arctan2'                 : 'ARCTAN2',                # ['Math']
    'Hyperbolic Sine'         : 'SINH',                   # ['Math']
    'Hyperbolic Cosine'       : 'COSH',                   # ['Math']
    'Hyperbolic Tangent'      : 'TANH',                   # ['Math']
    'To Radians'              : 'RADIANS',                # ['Math']
    'To Degrees'              : 'DEGREES',                # ['Math']
    'Mix'                     : 'MIX',                    # ['Mix']
    'Darken'                  : 'DARKEN',                 # ['Mix']
    'Color Burn'              : 'BURN',                   # ['Mix']
    'Lighten'                 : 'LIGHTEN',                # ['Mix']
    'Screen'                  : 'SCREEN',                 # ['Mix']
    'Color Dodge'             : 'DODGE',                  # ['Mix']
    'Overlay'                 : 'OVERLAY',                # ['Mix']
    'Soft Light'              : 'SOFT_LIGHT',             # ['Mix']
    'Linear Light'            : 'LINEAR_LIGHT',           # ['Mix']
    'Exclusion'               : 'EXCLUSION',              # ['Mix']
    'Hue'                     : 'HUE',                    # ['Mix']
    'Saturation'              : 'SATURATION',             # ['Mix']
    'Color'                   : 'COLOR',                  # ['Mix']
    'Value'                   : 'VALUE',                  # ['Mix']
    'Non-Uniform'             : 'NON_UNIFORM',            # ['Mix']
    '2D'                      : '2D',                     # ['Gabor Texture', 'Noise Texture', 'Voronoi Texture', 'White Noise Texture']
    '3D'                      : '3D',                     # ['Gabor Texture', 'Noise Texture', 'Voronoi Texture', 'White Noise Texture']
    'Quadratic'               : 'QUADRATIC',              # ['Gradient Texture']
    'Easing'                  : 'EASING',                 # ['Gradient Texture']
    'Diagonal'                : 'DIAGONAL',               # ['Gradient Texture', 'Wave Texture']
    'Spherical'               : 'SPHERICAL',              # ['Gradient Texture', 'Wave Texture']
    'Quadratic Sphere'        : 'QUADRATIC_SPHERE',       # ['Gradient Texture']
    'Radial'                  : 'RADIAL',                 # ['Gradient Texture']
    '1D'                      : '1D',                     # ['Noise Texture', 'Voronoi Texture', 'White Noise Texture']
    '4D'                      : '4D',                     # ['Noise Texture', 'Voronoi Texture', 'White Noise Texture']
    'Multifractal'            : 'MULTIFRACTAL',           # ['Noise Texture']
    'Ridged Multifractal'     : 'RIDGED_MULTIFRACTAL',    # ['Noise Texture']
    'Hybrid Multifractal'     : 'HYBRID_MULTIFRACTAL',    # ['Noise Texture']
    'fBM'                     : 'FBM',                    # ['Noise Texture']
    'Hetero Terrain'          : 'HETERO_TERRAIN',         # ['Noise Texture']
    'Euclidean'               : 'EUCLIDEAN',              # ['Voronoi Texture']
    'Manhattan'               : 'MANHATTAN',              # ['Voronoi Texture']
    'Chebychev'               : 'CHEBYCHEV',              # ['Voronoi Texture']
    'Minkowski'               : 'MINKOWSKI',              # ['Voronoi Texture']
    'F1'                      : 'F1',                     # ['Voronoi Texture']
    'F2'                      : 'F2',                     # ['Voronoi Texture']
    'Smooth F1'               : 'SMOOTH_F1',              # ['Voronoi Texture']
    'Distance to Edge'        : 'DISTANCE_TO_EDGE',       # ['Voronoi Texture']
    'N-Sphere Radius'         : 'N_SPHERE_RADIUS',        # ['Voronoi Texture']
    'Sin'                     : 'SIN',                    # ['Wave Texture']
    'Saw'                     : 'SAW',                    # ['Wave Texture']
    'Tri'                     : 'TRI',                    # ['Wave Texture']
    'Bands'                   : 'BANDS',                  # ['Wave Texture']
    'Rings'                   : 'RINGS',                  # ['Wave Texture']
    'Cross Product'           : 'CROSS_PRODUCT',          # ['Vector Math']
    'Project'                 : 'PROJECT',                # ['Vector Math']
    'Reflect'                 : 'REFLECT',                # ['Vector Math']
    'Refract'                 : 'REFRACT',                # ['Vector Math']
    'Faceforward'             : 'FACEFORWARD',            # ['Vector Math']
    'Distance'                : 'DISTANCE',               # ['Vector Math']
    'Scale'                   : 'SCALE',                  # ['Vector Math']
    'Normalize'               : 'NORMALIZE',              # ['Vector Math']
    'Fraction'                : 'FRACTION',               # ['Vector Math']
    'Axis Angle'              : 'AXIS_ANGLE',             # ['Vector Rotate']
    'X Axis'                  : 'X_AXIS',                 # ['Vector Rotate']
    'Y Axis'                  : 'Y_AXIS',                 # ['Vector Rotate']
    'Z Axis'                  : 'Z_AXIS',                 # ['Vector Rotate']
    'Euler XYZ'               : 'EULER_XYZ',              # ['Vector Rotate']

    # Shader

    'Geometry'                : 'GEOMETRY',               # ['Attribute']
    'Object'                  : 'OBJECT',                 # ['Attribute', 'Displacement', 'Normal Map', 'Point Density', 'Vector Displacement', 'Vector Transform', 'Vector Transform']
    'Instancer'               : 'INSTANCER',              # ['Attribute']
    'View Layer'              : 'VIEW_LAYER',             # ['Attribute']
    'Beckmann'                : 'BECKMANN',               # ['Glossy BSDF', 'Glass BSDF', 'Metallic BSDF', 'Refraction BSDF']
    'GGX'                     : 'GGX',                    # ['Glossy BSDF', 'Glass BSDF', 'Metallic BSDF', 'Principled BSDF', 'Refraction BSDF']
    'Ashikhmin-Shirley'       : 'ASHIKHMIN_SHIRLEY',      # ['Glossy BSDF']
    'Multiscatter GGX'        : 'MULTI_GGX',              # ['Glossy BSDF', 'Glass BSDF', 'Metallic BSDF', 'Principled BSDF']
    'Reflection'              : 'Reflection',             # ['Hair BSDF']
    'Transmission'            : 'Transmission',           # ['Hair BSDF']
    'Chiang'                  : 'CHIANG',                 # ['Principled Hair BSDF']
    'Huang'                   : 'HUANG',                  # ['Principled Hair BSDF']
    'Absorption'              : 'ABSORPTION',             # ['Principled Hair BSDF']
    'Melanin'                 : 'MELANIN',                # ['Principled Hair BSDF']
    'Physical Conductor'      : 'PHYSICAL_CONDUCTOR',     # ['Metallic BSDF']
    'F82'                     : 'F82',                    # ['Metallic BSDF']
    'Burley'                  : 'BURLEY',                 # ['Principled BSDF', 'Subsurface Scattering']
    'Random Walk'             : 'RANDOM_WALK',            # ['Principled BSDF', 'Subsurface Scattering']
    'Random Walk (Skin)'      : 'RANDOM_WALK_SKIN',       # ['Principled BSDF', 'Subsurface Scattering']
    'Ashikhmin'               : 'ASHIKHMIN',              # ['Sheen BSDF']
    'Microfiber'              : 'MICROFIBER',             # ['Sheen BSDF']
    'Diffuse'                 : 'DIFFUSE',                # ['Toon BSDF']
    'Glossy'                  : 'GLOSSY',                 # ['Toon BSDF']
    'World'                   : 'WORLD',                  # ['Displacement', 'Normal Map', 'Vector Displacement', 'Vector Transform', 'Vector Transform']
    'Point'                   : 'POINT',                  # ['Mapping', 'Vector Transform']
    'Texture'                 : 'TEXTURE',                # ['Mapping']
    'Normal'                  : 'NORMAL',                 # ['Mapping', 'Vector Transform']
    'Blender Object'          : 'BLENDER_OBJECT',         # ['Normal Map']
    'Blender World'           : 'BLENDER_WORLD',          # ['Normal Map']
    'EEVEE'                   : 'EEVEE',                  # ['Light Output', 'Line Style Output', 'Material Output', 'World Output']
    'Cycles'                  : 'CYCLES',                 # ['Light Output', 'Line Style Output', 'Material Output', 'World Output']
    'Internal'                : 'INTERNAL',               # ['Script', 'IES Texture']
    'External'                : 'EXTERNAL',               # ['Script', 'IES Texture']
    'UU Map'                  : 'UV_MAP',                 # ['Tangent']
    'Smart'                   : 'Smart',                  # ['Environment Texture', 'Image Texture']
    'Equirectangular'         : 'EQUIRECTANGULAR',        # ['Environment Texture']
    'Mirror Ball'             : 'MIRROR_BALL',            # ['Environment Texture']
    'Flat'                    : 'FLAT',                   # ['Image Texture']
    'Sphere'                  : 'SPHERE',                 # ['Image Texture']
    'Tube'                    : 'TUBE',                   # ['Image Texture']
    'Particle_Age'            : 'PARTICLE_AGE',           # ['Point Density']
    'Particle_Speed'          : 'PARTICLE_SPEED',         # ['Point Density']
    'Particle Velocity'       : 'PARTICLE_VELOCITY',      # ['Point Density']
    'Particle System'         : 'PARTICLE_SYSTEM',        # ['Point Density']
    'Object Vertices'         : 'OBJECT',                 # ['Point Density']
    'Object Space'            : 'OBJECT',                 # ['Point Density']
    'World Space'             : 'World',                  # ['Point Density']
    'Vertex Color'            : 'VERTEX_COLOR',           # ['Point Density']
    'Vertex Weight'           : 'VERTEX_WEIGHT',          # ['Point Density']
    'Vertex Normal'           : 'VERTEX_NORMAL',          # ['Point Density']
    'Preetham'                : 'PREETHAM',               # ['Sky Texture']
    'Hosek / Wilkie'          : 'HOSEK_WILKIE',           # ['Sky Texture']
    'Nishita'                 : 'NISHITA',                # ['Sky Texture']
    'Camera'                  : 'CAMERA',                 # ['Vector Transform', 'Vector Transform']
    'Henyey§Greenstein'       : 'HENYEY_GREENSTEIN',      # ['Volume Scatter']
    'Fournier§Forand'         : 'FOURNIER_FORAND',        # ['Volume Scatter']
    'Draine'                  : 'DRAINE',                 # ['Volume Scatter']
    'Rayleigh'                : 'RAYLEIGH',               # ['Volume Scatter']
    'Mie'                     : 'MIE',                    # ['Volume Scatter']

}
